language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

before_script:
  - composer self-update
  - composer install

script:
  - phpunit
  - tests/run-tests.sh
